Skip O/S's whose GLIBC is too old for Node 20 required by GitHub Actions.

diff --git a/.github/workflows/pkg-rust.yml b/.github/workflows/pkg-rust.yml
--- a/.github/workflows/pkg-rust.yml
+++ b/.github/workflows/pkg-rust.yml
@@ -399,6 +399,17 @@ jobs:
             fi
           fi
 
+          # Exclude ubuntu:bionic as its GLIBC is too old to support Node 20 now required to use GitHub Actions
+          if [[ "${PACKAGE_BUILD_RULES_PROCESSED_JSON}" != "{}" ]]; then
+            CONTROL_JSON=$(echo ${PACKAGE_BUILD_RULES_PROCESSED_JSON} | jq -c)
+            MODIFIED_JSON=$(echo ${PACKAGE_BUILD_RULES_PROCESSED_JSON} | jq -c 'del(.image[]? | select(. == "ubuntu:bionic")) | del(.include[]? | select(.image == "ubuntu:bionic"))')
+            MODIFIED_JSON=$(echo ${MODIFIED_JSON} | jq -c 'del(.include[]? | select(.os == "ubuntu:bionic"))')
+            if [[ "${CONTROL_JSON}" != "${MODIFIED_JSON}" ]]; then
+              echo "::warning::Removed ubuntu:bionic image from package_build_rules because its GLIBC is too old to support Node 20 required by GitHub Actions"
+              PACKAGE_BUILD_RULES_PROCESSED_JSON="${MODIFIED_JSON}"
+            fi
+          fi
+
           echo "package_build_rules<<END_OF_PACKAGE_BUILD_RULES" >> $GITHUB_OUTPUT
           echo ${PACKAGE_BUILD_RULES_PROCESSED_JSON} | jq >> $GITHUB_OUTPUT
           echo 'END_OF_PACKAGE_BUILD_RULES' >> $GITHUB_OUTPUT
@@ -851,35 +862,8 @@ jobs:
       CARGO_GENERATE_RPM_VER: 0.10.2
       TOML_CLI_VER: 0.2.3
     steps:
-    # Allow CentOS 8 to continue working now that it is EOL
-    # See: https://stackoverflow.com/a/70930049
-    - name: CentOS 8 EOL workaround
-      if: ${{ matrix.image == 'centos:8' }}
-      run: |
-        sed -i -e 's|mirrorlist=|#mirrorlist=|g' -e 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*
-    
-    # See: https://github.com/NLnetLabs/ploutos
-    # See: https://lists.debian.org/debian-devel-announce/2023/03/msg00006.html
-    # See: https://unix.stackexchange.com/a/743865
-    - name: Debian Stretch workaround
-      if: ${{ matrix.image == 'debian:stretch' }}
-      run: |
-        echo "deb http://archive.debian.org/debian stretch main" > /etc/apt/sources.list
-        echo "deb http://archive.debian.org/debian-security stretch/updates main" >> /etc/apt/sources.list
-
     - name: Checkout repository
-      # actions use node v20 which doesn't work on containers with older GLIBC such as ubuntu:bionic or centos:7
-      #uses: actions/checkout@v3 
-      run: |
-        if type apt-get &>/dev/null; then
-          apt-get update
-          apt-get install -y git
-        elif type yum &>/dev/null; then
-          #sed -i -e 's/enabled=1/enabled=0/' /etc/yum/pluginconf.d/fastestmirror.conf || true
-          yum update -y # See: https://github.com/NLnetLabs/ploutos/issues/90
-          yum install -y git
-        fi
-        git clone ${{ github.server_url }}/${{ github.repository }} --branch ${{ github.ref_name }} --single-branch $GITHUB_WORKSPACE
+      uses: actions/checkout@v3 # v4 doesn't work on containers with older GLIBC such as ubuntu:bionic or centos:7
 
     - name: Print matrix
       # Disable default use of bash -x for easier to read output in the log
@@ -953,12 +937,29 @@ jobs:
         echo "OS_NAME=${IMAGE%:*}" >> $GITHUB_ENV
         echo "OS_REL=${IMAGE#*:}" >> $GITHUB_ENV
 
+    # Allow CentOS 8 to continue working now that it is EOL
+    # See: https://stackoverflow.com/a/70930049
+    - name: CentOS 8 EOL workaround
+      if: ${{ matrix.image == 'centos:8' }}
+      run: |
+        sed -i -e 's|mirrorlist=|#mirrorlist=|g' -e 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*
+    
+    # See: https://github.com/NLnetLabs/ploutos
+    # See: https://lists.debian.org/debian-devel-announce/2023/03/msg00006.html
+    # See: https://unix.stackexchange.com/a/743865
+    - name: Debian Stretch workaround
+      if: ${{ matrix.image == 'debian:stretch' }}
+      run: |
+        echo "deb http://archive.debian.org/debian stretch main" > /etc/apt/sources.list
+        echo "deb http://archive.debian.org/debian-security stretch/updates main" >> /etc/apt/sources.list
+
     # Install Rust the hard way rather than using a GH Action because the action doesn't work inside a Docker container.
     - name: Install Rust
       id: rust
       run: |
         case ${OS_NAME} in
           debian|ubuntu)
+            apt-get update
             apt-get install -y curl
             ;;
         esac
@@ -988,6 +989,8 @@ jobs:
             apt-get install -y binutils gcc dpkg-dev jq lintian pkg-config ${{ inputs.deb_extra_build_packages }}
             ;;
           centos|rockylinux)
+            #sed -i -e 's/enabled=1/enabled=0/' /etc/yum/pluginconf.d/fastestmirror.conf || true
+            yum update -y # See: https://github.com/NLnetLabs/ploutos/issues/90
             yum install epel-release -y
             yum install -y findutils gcc jq ${{ inputs.rpm_extra_build_packages }}
 
