Support per package RPM scriptlets.

diff --git a/.github/workflows/pkg-rust.yml b/.github/workflows/pkg-rust.yml
--- a/.github/workflows/pkg-rust.yml
+++ b/.github/workflows/pkg-rust.yml
@@ -1112,7 +1112,11 @@ jobs:
             # Ugly hack to use an alternate base Cargo Generate RPM configuration so that the selected variant overrides
             # settings specified alternate base settings instead of the usual [package.metadata.generate-rpm] base
             # settings.
+            RPM_SCRIPTLETS_PATH="${{ inputs.rpm_scriptlets_path }}"
             if grep -Eq "^\[package\.metadata\.generate-rpm-alt-base-${MATRIX_PKG}\]$" Cargo.toml; then
+              if [[ "${RPM_SCRIPTLETS_PATH}" != "" ]]; then
+                RPM_SCRIPTLETS_PATH="${RPM_SCRIPTLETS_PATH}-${MATRIX_PKG}"
+              fi
               sed -i -e "s/^\[package\.metadata\.generate-rpm\]/[package.metadata.moved-generate-rpm]/" \
                      -e "s/^\[package\.metadata\.generate-rpm-alt-base-${MATRIX_PKG}\]/[package.metadata.generate-rpm]/" Cargo.toml
             fi
@@ -1123,7 +1127,12 @@ jobs:
             # can be executed (hence post-uninstall rather than pre-uninstall...). So instead embed the entire
             # uninstall script in the TOML settings using the cargo-generate-rpm --set-metadata (aka -s)
             # command line argument.
-            if [[ "${{ inputs.rpm_scriptlets_path }}" != "" ]]; then
+            if [[ "${RPM_SCRIPTLETS_PATH}" != "" ]]; then
+              if [ ! -f "${RPM_SCRIPTLETS_PATH}" ]; then
+                echo "::error::File '${RPM_SCRIPTLETS_PATH}' does not exist."
+                exit 1
+              fi
+  
               # Download the RPM systemd macros shell functions file fragment
               SYSTEMD_RPM_MACROS_URL="https://raw.githubusercontent.com/NLnetLabs/ploutos/v5.2.0/fragments/macros.systemd.sh"
               SYSTEMD_RPM_MACROS_FILE="/tmp/systemd_rpm_macros"
